version: '3'
services:
  myapp:
    image: myapp-image
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://oe.cezoarjq4rjn.ap-northeast-2.rds.amazonaws.com:3306/OE
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: qlalfqjsghwkdtmddus
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MAIL_SMTP_AUTH: "true"
      MAIL_SMTP_STARTTLS_REQUIRED: "true"
      MAIL_SMTP_STARTTLS_ENABLE: "true"
      MAIL_SMTP_SOCKETFACTORY_CLASS: javax.net.ssl.SSLSocketFactory
      MAIL_SMTP_SOCKETFACTORY_FALLBACK: "false"
      MAIL_SMTP_PORT: 465
      MAIL_SMTP_SOCKETFACTORY_PORT: 465
      ADMINMAIL_ID: jangsy1207@gmail.com
      ADMINMAIL_PASSWORD: bvtmlykxaxrsacuj
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"